name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: go-semantic-release/action@v1
        id: semrel
        with:
          github-token: ${{ secrets.PATH_FINDING_TOKEN }}
          changelog-generator-opt: "emojis=true"